/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface ProfileUpdatePayload {
  bio?: string | null;
  birthDate?: Date | null;
  fullName?: string | null;
  genderId?: string | null;
  hometown?: string | null;
  location?: string | null;
}

export interface ProfileUpdatePreferencePayload {
  genderId: string;
  maxAge: number;
  minAge: number;
  radius?: number;
}
