/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface UserEmailCheckPayload {
  email: string;
}

export interface UserGetParams {
  userId: string;
}

export interface UserLoginPayload {
  identifier: string;
  pin: string;
}

export interface UserPhoneNumberCheckPayload {
  phoneNumber: string;
}

export interface UserRegisterPayload {
  email?: string | null;
  phoneNumber: string;
  pin: string;
  username: string;
}
